name: Server Bug Report
description: Report a bug encountered while operating AWS IAM Authenticator Server
title: "[Bug]: "
labels: ["kind/bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please use this template while reporting a server bug and provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner. Thanks!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-did-you-expect
    attributes:
      label: What you expected to happen?
      placeholder: Tell us what you want to see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else we need to know?
    validations:
      required: false
  - type: dropdown
    id: installation
    attributes:
      label: Installation tooling
      description: How did you install aws-iam-authenticator server?
      options:
        - kOps
        - eks-anywhere
        - other (please specify in description)
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: AWS IAM Authenticator server Version
      description: What version of the aws-iam-authenticator are you running?
      placeholder: Output from `aws-iam-authenticator version`
    validations:
      required: true
  - type: textarea
    id: client
    attributes:
      label: Client information
      description: |
        examples:
          - **OS/arch**: Ubuntu 20.04 x86 or macOS 12.5.1 intel
          - **kubernetes client & version**: kubectl or kubelet
          - **authenticator client & version**: aws-cli/2.8.12 or aws-ium-authenticator v0.6.0
      value: |
        - OS/arch:
        - kubernetes client & version:
        - authenticator client & version:
      render: Markdown
    validations:
      required: false
  - type: input
    id: k8s-version
    attributes:
      label: Kubernetes API Version
      description: What version of the Kubernetes API are you running?
      placeholder: Output from `kubectl version`
    validations:
      required: true
  - type: textarea
    id: authenticator-manifest
    attributes:
      label: aws-iam-authenticator YAML manifest
      description: Please copy and paste the install YAML. This will be automatically formatted into yaml, so no need for backticks.
      render: YAML
  - type: textarea
    id: kube-apiserver-manifest
    attributes:
      label: kube-apiserver YAML manifest
      description: Please copy and paste the kube-apiserver YAML. This will be automatically formatted into yaml, so no need for backticks.
      render: YAML
  - type: textarea
    id: authenticator-logs
    attributes:
      label: aws-iam-authenticator logs
      description: Please copy and paste the relevant logs. This will be automatically formatted into json, so no need for backticks.
      render: JSON
