- name: <CLUSTER_NAME>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: <AUTHENTICATOR_BIN>
      args:
        - "token"
        - "-i"
        - <CLUSTER_NAME>
        - "-r"
        - <ADMIN_ROLE>
