name: "Dependency Review"

on: [pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency review
        uses: actions/dependency-review-action@v4

  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-file: go.mod

      # [Info] Shows version of go that is (was) used
      - run: go version
