name: tag-release

on:
  push:
    branches:
      - 'release-*'
    paths:
      - version.txt

jobs:
  tag-release:
    if: ${{ github.repository == 'kubernetes-sigs/aws-iam-authenticator' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: "${{ secrets.RELEASE_KEY }}"

      - name: Tag release
        run: |
          /usr/bin/git config --global user.email actions@github.com
          /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
          hack/tag-release.sh
